# Generated by Django 3.0.5 on 2020-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200429_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='githubLink',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='otherLink',
            field=models.CharField(max_length=250),
        ),
    ]
