# Generated by Django 3.0.5 on 2020-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200429_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imgCode',
            field=models.CharField(default='precursorlogo.png', max_length=250),
            preserve_default=False,
        ),
    ]
