# Generated by Django 3.0.5 on 2020-05-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_project_imgcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='otherLinkName',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
